# -----------* Email Service *-----------
email_address = "YourEmail@hotmail.com / YourEmail@outlook.com"
login_password = "YourPassword"
imap_server_address = "outlook.office365.com"
imap_server_port = 993

# --------------* Webhook *--------------
webhook_urls = [
    "Webhook URL",
    ]

# ----------------* Log *----------------
# save log as a text file
log_save = true

# console log with color
log_color = true

# include the current time zone into the log
log_time_zone = false

# highlight the log with the same color with log label
log_full_color = false